export const RIPS_FETCH_START = 'RIPS_FETCH_START';
export const RIPS_FETCH_SUCCESS = 'RIPS_FETCH_SUCCESS';
export const RIPS_FETCH_FAIL = 'RIPS_FETCH_FAIL';
export const RIPS_ADD_USER_DATA = 'RIPS_ADD_USER_DATA';
// export const RIPS_FETCH_WORDS = 'RIPS_FETCH_WORDS';

export const BACKGROUND_PORT_SET = 'BACKGROUND_PORT_SET';
export const BACKGROUND_PORT_REMOVE = 'BACKGROUND_PORT_REMOVE';
export const BACKGROUND_PORT_ERROR = 'BACKGROUND_PORT_ERROR';
export const PORT_INIT_COLLECT = 'PORT_INIT_COLLECT';
// export const BACKGROUND_PORT_INIT = 'BACKGROUND_PORT_INIT';