export const BLANK_ACTION = 'BLANK_ACTION';

export const RIPS_FETCH_START = 'RIPS_FETCH_START';
export const RIPS_FETCH_SUCCESS = 'RIPS_FETCH_SUCCESS';
export const RIPS_FETCH_FAIL = 'RIPS_FETCH_FAIL';
// const RIPS_FETCH_DATA... (container - no action connected to reducer)

export const BACKGROUND_PORT_SET = 'BACKGROUND_PORT_SET';
export const BACKGROUND_PORT_REMOVE = 'BACKGROUND_PORT_REMOVE';
export const BACKGROUND_PORT_ERROR = 'BACKGROUND_PORT_ERROR';
export const PORT_INIT_COLLECT = 'PORT_INIT_COLLECT';
// const BACKGROUND_PORT_INIT... (container - no action connected to reducer)

export const TABLE_ADD_CLIENT_DATA = 'TABLE_ADD_CLIENT_DATA';
export const TABLE_ADD_SELECTED = 'TABLE_ADD_SELECTED';
export const TABLE_CALC_UNSELECTED = 'TABLE_CALC_UNSELECTED';